"""add slug column to products table

Revision ID: abd495c87e88
Revises: 9bb4f22420a0
Create Date: 2023-05-27 22:10:18.883789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd495c87e88'
down_revision = '9bb4f22420a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'slug')
    # ### end Alembic commands ###
